version: "3.3"
services:
  ros2ubuntu: &ros2ubuntu
    container_name: ros2ubuntu
    image: ros2ubuntu:latest
    ipc: host
    network_mode: host
    privileged: true
    environment:
      - DISPLAY
      - XAUTHORITY=/tmp/.Xauthority
    volumes:
      - $HOME/$USER/fyp/shared/:/root/fyp/shared/
      - $HOME/.Xauthority:/tmp/.Xauthority
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /dev:/dev
    command: ["tail", "-f", "/dev/null"]

  # The following is taken from AutomaticAddison's Cobot repo - highly suggest to check it out - a lot of this project is inspired by or comes directly from there
  minimal_publisher:
    <<: *ros2ubuntu # This uses all the same settings as the 'ros2ubuntu' service
    container_name: minimal_publisher
    command: ["ros2", "run", "demo_nodes_cpp", "talker"]

  # Subscriber service: Runs the demo listener node
  minimal_subscriber:
    <<: *ros2ubuntu # This uses all the same settings as the 'ros2ubuntu' service
    container_name: minimal_subscriber
    command: ["ros2", "run", "demo_nodes_cpp", "listener"]
